"""Add case_messages table

Revision ID: e4258cb29a3a
Revises: 93eb45f23e2e
Create Date: 2026-08-10 05:47:25.305690+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4258cb29a3a'
down_revision: Union[str, None] = '93eb45f23e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_messages',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False, comment='The user who sent the message'),
    sa.Column('message_text', sa.Text(), nullable=False, comment='The content of the message'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Has the recipient read it?'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_messages_case_id'), 'case_messages', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_messages_sender_id'), 'case_messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_messages_sender_id'), table_name='case_messages')
    op.drop_index(op.f('ix_case_messages_case_id'), table_name='case_messages')
    op.drop_table('case_messages')
    # ### end Alembic commands ###
