"""Expand advocate model for onboarding

Revision ID: cbd0ddcb7bfc
Revises: e4258cb29a3a
Create Date: 2026-08-10 06:14:06.571439+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd0ddcb7bfc'
down_revision: Union[str, None] = 'e4258cb29a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advocates', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('advocates', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('advocates', sa.Column('bar_association', sa.String(length=200), nullable=True))
    op.add_column('advocates', sa.Column('practice_areas', sa.String(length=500), nullable=True))
    op.add_column('advocates', sa.Column('llb_degree', sa.String(length=200), nullable=True))
    op.add_column('advocates', sa.Column('university', sa.String(length=200), nullable=True))
    op.add_column('advocates', sa.Column('college', sa.String(length=200), nullable=True))
    op.add_column('advocates', sa.Column('graduation_year', sa.Integer(), nullable=True))
    op.add_column('advocates', sa.Column('degree_certificate_path', sa.String(length=500), nullable=True))
    op.add_column('advocates', sa.Column('state_bar_council', sa.String(length=200), nullable=True))
    op.add_column('advocates', sa.Column('enrollment_date', sa.String(length=50), nullable=True))
    op.add_column('advocates', sa.Column('enrollment_certificate_path', sa.String(length=500), nullable=True))
    op.add_column('advocates', sa.Column('aibe_status', sa.String(length=50), nullable=True))
    op.add_column('advocates', sa.Column('certificate_of_practice_path', sa.String(length=500), nullable=True))
    op.add_column('advocates', sa.Column('pan_number', sa.String(length=20), nullable=True))
    op.add_column('advocates', sa.Column('pan_document_path', sa.String(length=500), nullable=True))
    op.add_column('advocates', sa.Column('gov_id_path', sa.String(length=500), nullable=True))
    op.add_column('advocates', sa.Column('photograph_path', sa.String(length=500), nullable=True))
    op.add_column('advocates', sa.Column('verification_status', sa.String(length=50), server_default='pending', nullable=False))
    op.alter_column('advocates', 'bar_council_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Bar Council registration number',
               existing_nullable=True)
    op.alter_column('advocates', 'is_available',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               comment=None,
               existing_comment='Whether advocate is currently accepting new cases',
               existing_nullable=False)
    op.alter_column('advocates', 'experience_years',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Years of professional experience',
               existing_nullable=True)
    op.alter_column('advocates', 'bio',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Professional biography',
               existing_nullable=True)
    op.alter_column('advocates', 'signature_image',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Path to digital signature image file',
               existing_nullable=True)
    op.create_index(op.f('ix_advocates_verification_status'), 'advocates', ['verification_status'], unique=False)
    op.drop_column('advocates', 'court_practice')
    op.drop_column('advocates', 'qualification')
    op.drop_column('advocates', 'specialization')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advocates', sa.Column('specialization', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Area of legal specialization'))
    op.add_column('advocates', sa.Column('qualification', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Academic qualification (e.g., LLB, LLM)'))
    op.add_column('advocates', sa.Column('court_practice', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Courts where advocate practices'))
    op.drop_index(op.f('ix_advocates_verification_status'), table_name='advocates')
    op.alter_column('advocates', 'signature_image',
               existing_type=sa.VARCHAR(length=500),
               comment='Path to digital signature image file',
               existing_nullable=True)
    op.alter_column('advocates', 'bio',
               existing_type=sa.TEXT(),
               comment='Professional biography',
               existing_nullable=True)
    op.alter_column('advocates', 'experience_years',
               existing_type=sa.INTEGER(),
               comment='Years of professional experience',
               existing_nullable=True)
    op.alter_column('advocates', 'is_available',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Whether advocate is currently accepting new cases',
               existing_nullable=False)
    op.alter_column('advocates', 'bar_council_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Bar Council registration number',
               existing_nullable=True)
    op.drop_column('advocates', 'verification_status')
    op.drop_column('advocates', 'photograph_path')
    op.drop_column('advocates', 'gov_id_path')
    op.drop_column('advocates', 'pan_document_path')
    op.drop_column('advocates', 'pan_number')
    op.drop_column('advocates', 'certificate_of_practice_path')
    op.drop_column('advocates', 'aibe_status')
    op.drop_column('advocates', 'enrollment_certificate_path')
    op.drop_column('advocates', 'enrollment_date')
    op.drop_column('advocates', 'state_bar_council')
    op.drop_column('advocates', 'degree_certificate_path')
    op.drop_column('advocates', 'graduation_year')
    op.drop_column('advocates', 'college')
    op.drop_column('advocates', 'university')
    op.drop_column('advocates', 'llb_degree')
    op.drop_column('advocates', 'practice_areas')
    op.drop_column('advocates', 'bar_association')
    op.drop_column('advocates', 'district')
    op.drop_column('advocates', 'state')
    # ### end Alembic commands ###
