"""initial_create_all_tables

Revision ID: b2d5ae3ae3b2
Revises: 
Create Date: 2026-08-06 05:25:36.201974+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2d5ae3ae3b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False, comment='Role name (admin, advocate, client)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Role description'),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object defining granular permissions'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address (used for login)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='User first name'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='User last name'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Phone number with country code'),
    sa.Column('role_id', sa.UUID(), nullable=False, comment='Foreign key to roles table'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the user account is active'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Whether the user email is verified'),
    sa.Column('reset_token', sa.String(length=255), nullable=True, comment='Password reset token'),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True, comment='Password reset token expiry'),
    sa.Column('refresh_token', sa.String(length=500), nullable=True, comment='Hashed refresh token for token rotation'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('advocates',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Foreign key to users table'),
    sa.Column('bar_council_id', sa.String(length=50), nullable=True, comment='Bar Council registration number'),
    sa.Column('specialization', sa.String(length=200), nullable=True, comment='Area of legal specialization'),
    sa.Column('experience_years', sa.Integer(), nullable=True, comment='Years of professional experience'),
    sa.Column('qualification', sa.String(length=200), nullable=True, comment='Academic qualification (e.g., LLB, LLM)'),
    sa.Column('court_practice', sa.String(length=200), nullable=True, comment='Courts where advocate practices'),
    sa.Column('bio', sa.Text(), nullable=True, comment='Professional biography'),
    sa.Column('signature_image', sa.String(length=500), nullable=True, comment='Path to digital signature image file'),
    sa.Column('is_available', sa.Boolean(), nullable=False, comment='Whether advocate is currently accepting new cases'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advocates_bar_council_id'), 'advocates', ['bar_council_id'], unique=True)
    op.create_index(op.f('ix_advocates_user_id'), 'advocates', ['user_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User who performed the action'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Action performed (create, update, delete, login, logout, etc.)'),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='Type of resource affected (user, case, payment, etc.)'),
    sa.Column('resource_id', sa.UUID(), nullable=True, comment='ID of the affected resource'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address (supports IPv6)'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='Client user agent string'),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Previous values before the change'),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='New values after the change'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('clients',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Foreign key to users table'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='Full postal address'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='City name'),
    sa.Column('state', sa.String(length=100), nullable=True, comment='State/Province'),
    sa.Column('pincode', sa.String(length=10), nullable=True, comment='PIN/ZIP code'),
    sa.Column('aadhar_number', sa.String(length=20), nullable=True, comment='Aadhar card number (encrypted at rest)'),
    sa.Column('pan_number', sa.String(length=20), nullable=True, comment='PAN card number'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal notes about the client'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Recipient user ID'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Notification type (case_update, payment, report_ready, etc.)'),
    sa.Column('title', sa.String(length=300), nullable=False, comment='Notification title'),
    sa.Column('message', sa.Text(), nullable=False, comment='Notification message body'),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='Delivery channel (in_app, email, whatsapp, sms)'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Whether notification has been read'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional data (case_id, payment_id, etc.)'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='When the notification was read'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('cases',
    sa.Column('case_number', sa.String(length=50), nullable=False, comment='Auto-generated case reference number (e.g., CASE-2026-0001)'),
    sa.Column('client_id', sa.UUID(), nullable=False, comment='Foreign key to clients table'),
    sa.Column('advocate_id', sa.UUID(), nullable=True, comment='Foreign key to advocates table (assigned later)'),
    sa.Column('title', sa.String(length=300), nullable=False, comment='Brief case title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed case description from client'),
    sa.Column('case_type', sa.String(length=100), nullable=True, comment='Type of case (civil, criminal, family, corporate, etc.)'),
    sa.Column('status', sa.Enum('NEW', 'PAYMENT_PENDING', 'PAYMENT_COMPLETED', 'PAYMENT_FAILED', 'DOCUMENTS_UPLOADED', 'AI_PROCESSING', 'UNDER_REVIEW', 'OPINION_GENERATED', 'REPORT_GENERATED', 'COMPLETED', 'CANCELLED', name='case_status_enum', create_constraint=True), nullable=False, comment='Current case status'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='case_priority_enum', create_constraint=True), nullable=False, comment='Case priority level'),
    sa.Column('court_name', sa.String(length=200), nullable=True, comment='Name of the court (if applicable)'),
    sa.Column('next_hearing_date', sa.Date(), nullable=True, comment='Next court hearing date'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['advocate_id'], ['advocates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_advocate_id'), 'cases', ['advocate_id'], unique=False)
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_cases_client_id'), 'cases', ['client_id'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('citation_library',
    sa.Column('added_by', sa.UUID(), nullable=True, comment='Advocate who added this citation'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Citation title or case name'),
    sa.Column('citation_type', sa.String(length=50), nullable=False, comment='Type: judgment, act, section, article'),
    sa.Column('act_name', sa.String(length=300), nullable=True, comment='Name of the act (if applicable)'),
    sa.Column('section_number', sa.String(length=50), nullable=True, comment='Section number within the act'),
    sa.Column('judgment_text', sa.Text(), nullable=True, comment='Full judgment text or excerpt'),
    sa.Column('court_name', sa.String(length=200), nullable=True, comment='Court that delivered the judgment'),
    sa.Column('judgment_date', sa.Date(), nullable=True, comment='Date of the judgment'),
    sa.Column('case_reference', sa.String(length=200), nullable=True, comment='Case citation reference (e.g., AIR 2020 SC 1234)'),
    sa.Column('notes', sa.Text(), nullable=True, comment="Advocate's personal notes on this citation"),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of keywords for search'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Category (criminal, civil, constitutional, etc.)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['added_by'], ['advocates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_library_added_by'), 'citation_library', ['added_by'], unique=False)
    op.create_index(op.f('ix_citation_library_category'), 'citation_library', ['category'], unique=False)
    op.create_index(op.f('ix_citation_library_citation_type'), 'citation_library', ['citation_type'], unique=False)
    op.create_table('ai_summaries',
    sa.Column('case_id', sa.UUID(), nullable=False, comment='Foreign key to cases table (one summary per case)'),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI-generated case summary'),
    sa.Column('important_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of key facts identified by AI'),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of {date, event} objects'),
    sa.Column('legal_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of identified legal issues'),
    sa.Column('suggested_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of relevant legal sections and acts'),
    sa.Column('suggested_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of recommended actions'),
    sa.Column('precedents', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of potentially relevant case precedents'),
    sa.Column('raw_response', sa.Text(), nullable=True, comment='Raw AI API response for debugging'),
    sa.Column('model_used', sa.String(length=50), nullable=True, comment='AI model used (gpt-4, claude-3, etc.)'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ai_summary_status_enum', create_constraint=True), nullable=False, comment='Processing status'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='When AI processing completed'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_summaries_case_id'), 'ai_summaries', ['case_id'], unique=True)
    op.create_table('case_documents',
    sa.Column('case_id', sa.UUID(), nullable=False, comment='Foreign key to cases table'),
    sa.Column('uploaded_by', sa.UUID(), nullable=True, comment='User who uploaded the document'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Stored file name (UUID-based to prevent conflicts)'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='Original file name as uploaded by user'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='Full path to the stored file'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME type (application/pdf, image/jpeg, etc.)'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash for duplicate detection'),
    sa.Column('document_type', sa.String(length=100), nullable=True, comment='Document category (contract, court_order, evidence, etc.)'),
    sa.Column('ocr_processed', sa.Boolean(), nullable=False, comment='Whether OCR has been performed on this document'),
    sa.Column('extracted_text', sa.Text(), nullable=True, comment='Text extracted from the document (via OCR or direct extraction)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_documents_case_id'), 'case_documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_documents_file_hash'), 'case_documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_case_documents_uploaded_by'), 'case_documents', ['uploaded_by'], unique=False)
    op.create_table('case_status_history',
    sa.Column('case_id', sa.UUID(), nullable=False, comment='Foreign key to cases table'),
    sa.Column('changed_by', sa.UUID(), nullable=True, comment='User who triggered the status change'),
    sa.Column('old_status', sa.String(length=50), nullable=True, comment='Previous status value'),
    sa.Column('new_status', sa.String(length=50), nullable=False, comment='New status value'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='Remarks or reason for the status change'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_status_history_case_id'), 'case_status_history', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_status_history_changed_by'), 'case_status_history', ['changed_by'], unique=False)
    op.create_table('legal_opinions',
    sa.Column('case_id', sa.UUID(), nullable=False, comment='Foreign key to cases table (one opinion per case)'),
    sa.Column('advocate_id', sa.UUID(), nullable=True, comment='Advocate who wrote the opinion'),
    sa.Column('ai_summary_edited', sa.Text(), nullable=True, comment="Advocate's edited version of the AI summary"),
    sa.Column('legal_opinion', sa.Text(), nullable=True, comment="Advocate's legal opinion and analysis"),
    sa.Column('winning_probability', sa.Integer(), nullable=True, comment='Estimated winning probability (0-100%)'),
    sa.Column('risk_assessment', sa.Text(), nullable=True, comment='Risk analysis and potential challenges'),
    sa.Column('recommended_actions', sa.Text(), nullable=True, comment='Recommended next steps for the client'),
    sa.Column('status', sa.Enum('DRAFT', 'FINALIZED', name='opinion_status_enum', create_constraint=True), nullable=False, comment='Opinion status (draft or finalized)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['advocate_id'], ['advocates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_opinions_advocate_id'), 'legal_opinions', ['advocate_id'], unique=False)
    op.create_index(op.f('ix_legal_opinions_case_id'), 'legal_opinions', ['case_id'], unique=True)
    op.create_table('payments',
    sa.Column('case_id', sa.UUID(), nullable=False, comment='Foreign key to cases table'),
    sa.Column('client_id', sa.UUID(), nullable=False, comment='Foreign key to clients table'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Payment amount'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='Payment currency (ISO 4217)'),
    sa.Column('payment_method', sa.Enum('UPI', 'DEBIT_CARD', 'CREDIT_CARD', 'NET_BANKING', 'WALLET', name='payment_method_enum', create_constraint=True), nullable=True, comment='Payment method used'),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True, comment='Razorpay order ID'),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True, comment='Razorpay payment ID (received after successful payment)'),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True, comment='Razorpay payment signature for verification'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status_enum', create_constraint=True), nullable=False, comment='Payment status'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional payment metadata'),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True, comment='When payment was completed'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id'),
    sa.UniqueConstraint('razorpay_payment_id')
    )
    op.create_index(op.f('ix_payments_case_id'), 'payments', ['case_id'], unique=False)
    op.create_index(op.f('ix_payments_client_id'), 'payments', ['client_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('case_id', sa.UUID(), nullable=False, comment='Foreign key to cases table (one report per case)'),
    sa.Column('generated_by', sa.UUID(), nullable=True, comment='User who generated the report'),
    sa.Column('report_type', sa.String(length=50), nullable=False, comment='Type of report (legal_opinion, consultation, etc.)'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='Path to the generated PDF file'),
    sa.Column('file_name', sa.String(length=255), nullable=True, comment='Generated PDF file name'),
    sa.Column('has_signature', sa.Boolean(), nullable=False, comment='Whether the report includes a digital signature'),
    sa.Column('has_watermark', sa.Boolean(), nullable=False, comment='Whether the report includes a watermark'),
    sa.Column('status', sa.Enum('GENERATING', 'COMPLETED', 'FAILED', name='report_status_enum', create_constraint=True), nullable=False, comment='Report generation status'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional report metadata (page count, generation time, etc.)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_case_id'), 'reports', ['case_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_case_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_client_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_case_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_legal_opinions_case_id'), table_name='legal_opinions')
    op.drop_index(op.f('ix_legal_opinions_advocate_id'), table_name='legal_opinions')
    op.drop_table('legal_opinions')
    op.drop_index(op.f('ix_case_status_history_changed_by'), table_name='case_status_history')
    op.drop_index(op.f('ix_case_status_history_case_id'), table_name='case_status_history')
    op.drop_table('case_status_history')
    op.drop_index(op.f('ix_case_documents_uploaded_by'), table_name='case_documents')
    op.drop_index(op.f('ix_case_documents_file_hash'), table_name='case_documents')
    op.drop_index(op.f('ix_case_documents_case_id'), table_name='case_documents')
    op.drop_table('case_documents')
    op.drop_index(op.f('ix_ai_summaries_case_id'), table_name='ai_summaries')
    op.drop_table('ai_summaries')
    op.drop_index(op.f('ix_citation_library_citation_type'), table_name='citation_library')
    op.drop_index(op.f('ix_citation_library_category'), table_name='citation_library')
    op.drop_index(op.f('ix_citation_library_added_by'), table_name='citation_library')
    op.drop_table('citation_library')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_client_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_index(op.f('ix_cases_advocate_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_advocates_user_id'), table_name='advocates')
    op.drop_index(op.f('ix_advocates_bar_council_id'), table_name='advocates')
    op.drop_table('advocates')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
