"""Add CMS models

Revision ID: fe6e7b2f8bf6
Revises: ddb1b28f4441
Create Date: 2026-08-17 09:33:07.401283+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6e7b2f8bf6'
down_revision: Union[str, None] = 'ddb1b28f4441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('featured_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('faqs',
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_sections',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('primary_cta_text', sa.String(length=50), nullable=True),
    sa.Column('primary_cta_link', sa.String(length=255), nullable=True),
    sa.Column('secondary_cta_text', sa.String(length=50), nullable=True),
    sa.Column('secondary_cta_link', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_contents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('practice_areas',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('detailed_content', sa.Text(), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('website_settings',
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('office_hours', sa.String(length=255), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('footer_text', sa.Text(), nullable=True),
    sa.Column('copyright_text', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cases', 'client_rating',
               existing_type=sa.INTEGER(),
               comment='Client rating (1-5)',
               existing_nullable=True)
    op.alter_column('cases', 'client_review',
               existing_type=sa.TEXT(),
               comment='Client feedback review',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'client_review',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Client feedback review',
               existing_nullable=True)
    op.alter_column('cases', 'client_rating',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Client rating (1-5)',
               existing_nullable=True)
    op.drop_table('website_settings')
    op.drop_table('practice_areas')
    op.drop_table('page_contents')
    op.drop_table('hero_sections')
    op.drop_table('faqs')
    op.drop_table('blogs')
    # ### end Alembic commands ###
