"""Add missing user preferences column

Revision ID: 326e11b48d5e
Revises: cbd0ddcb7bfc
Create Date: 2026-08-12 10:38:27.045652+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326e11b48d5e'
down_revision: Union[str, None] = 'cbd0ddcb7bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferences', sa.JSON(), server_default='{}', nullable=False, comment='JSON object storing user specific settings (e.g., email_notifications)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    # ### end Alembic commands ###
